### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by dumblob** [Kindelia/LambdaVM-Rust#2]
I wonder what's the motivation behind rewriting the VM in Rust? Don't you lose one of the major selling points (verifiable VM)?

**Comment by MaiaVictor** [comment]
Why would it being in C be more verifiable?

Previously, it was written mostly in Deno (the utils, parsers, etc.), with TypeScript, and the runtime itself in C. There was no motivation for that, other than me being comfortable with these. TypeScript is not a language I trust for serious projects that require long-term maintenance. I almost trust Rust, though. It is safe, fast, the quality of its libs and ecosystem is overwhelmingly superior, and, honestly, its compiler is pedantic enough to scare away developers that will probably write shitty code. My current plan is to write the low level stuff in Rust (the runtime, perhaps some IO tools), and the high-level stuff in LambdaVM's language itself.

**Comment by rigille** [comment]
Rust type-system gives more guarantees by default, However C has a formal semantics and a verified compiler so you can take verification all the way to full proofs of correctness if you're willing to do this much work. Maybe that's what @dumblob means? We don't have the resources to deep spec the VM, so I think Rust makes more sense.

**Comment by MaiaVictor** [comment]
To be fair it never even crossed my mind that "verifiable" would be an important aspect of the VM. I just want the fastest functional runtime that computers can execute.

**Comment by dumblob** [comment]
Thanks a lot for explanations and insights. It seems this is a huge oversight on my side and I'm truly sorry for that. I thought (without checking the previous code) you rewrote it from *Kind* to Rust.

It's true that C is (potentially) verifiable (unlike Rust, unlike C++, etc.). But I totally agree that it won't add much.

And yeah I fully agree with the choice of Rust over TypeScript or any other language for this purpose.

So I'm closing this issue as invalid. Thanks again for your patience!

**Comment by MaiaVictor** [comment]
Wait, this issue is totally valid and this is a great question. Why are you asking sorry? Thanks for asking it!
